artifacts_root :  artifacts

data_ingestion : 
  root_dir : artifacts/data_ingestion
  source_URL : https://github.com/ZeeshanML/End-to-End-Red-Wine-Quality-Prediction-Project/raw/main/data/wineQuality-data.zip
  local_data_file : artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion
  

data_validation :
  root_dir : artifacts/data_validation
  unzip_data_dir : artifacts/data_ingestion/WineQT.csv
  STATUS_FILE : artifacts/data_validation/status.txt


data_transformation :
  root_dir : artifacts/data_transformation
  data_path : artifacts/data_ingestion/WineQT.csv
  preprocessed_data_path : artifacts/data_transformation/preprocessed_data.csv


model_trainer :
  root_dir : artifacts/model_trainer
  train_data_path : artifacts/data_transformation/train.csv
  test_data_path : artifacts/data_transformation/test.csv
  model_name : model.joblib
