artifacts_root :  artifacts

data_ingestion : 
  root_dir : artifacts/data_ingestion
  source_URL : https://github.com/ZeeshanML/End-to-End-Red-Wine-Quality-Prediction-Project/raw/main/data/wineQuality-data.zip
  local_data_file : artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion
  